import { SignInButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Image from "next/image";
import { type RouterOutputs, api } from "~/utils/api";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";

dayjs.extend(relativeTime);

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithUser) => {
  const { post, author } = props;

  return (
    <div className="flex items-center gap-2 border-b border-slate-400 p-4">
      <div>
        <Image
          src={author.imageUrl}
          alt="Author image"
          width={40}
          height={40}
          className="rounded-full"
        />
      </div>
      <div>
        <div className="flex gap-1 font-bold">
          <span> {`@${author.username}`}</span>
          <span className="font-thin">·</span>
          <span className="font-thin">{dayjs(post.createdAt).fromNow()}</span>
        </div>
        <div>{post.content}</div>
      </div>
    </div>
  );
};

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) {
    return null;
  }

  return (
    <div className="flex gap-2">
      <Image
        src={user.imageUrl}
        alt="Profile image"
        width={60}
        height={60}
        className="rounded-full"
      />
      <input
        placeholder="Choose emoji"
        className="grow rounded-md border border-slate-600 bg-transparent p-2"
      />
    </div>
  );
};

export default function Home() {
  const { isSignedIn } = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) {
    return <div>Loading...</div>;
  }

  if (!data) {
    return <div>No posts</div>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="border-b border-slate-400 p-4">
            {isSignedIn && <CreatePostWizard />}
            {!isSignedIn && <SignInButton />}
          </div>
          <div className="flex flex-col space-y-2">
            {data.map((post) => (
              <PostView key={post.post.id} {...post} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
